#!/usr/bin/env python3
"""
KPP K302 - SAST Gating Issues
Counts total SAST security issues (High + Medium severity only) per team,
derived from the SAST HTML reports downloaded by the security_scan_fetch job.

Data source:  output/scans/sast/<project_id>_sast.html
              (HTML generated by HCL AppScan SAST; section "Summary of security issues")

Project-to-team mapping: config/security_scan_config.json
  - Each scan project has a "teams" list; if a team has multiple scan projects, counts are SUMMEd.

Output file: output/k302-data.csv
  - One row per team member per run (weekly snapshot).
  - File accumulates over time (one record per person per week kept).
  - Weekly  : current count from today's scan.
  - Monthly  : median of all recorded Weekly values in the current calendar month.
  - Quarterly: median of all recorded Weekly values in the current fiscal quarter.
  - Annual   : median of all recorded Weekly values in the current fiscal year.

Targets (from Roles.csv k302):
  Weekly: 0  |  Monthly: 15  |  Quarterly: 15  |  Annual: 15
Goal type: Lower is better (NL / ANL).
"""

import json
import os
import re
import sys
from datetime import date
from pathlib import Path

import pandas as pd

from kpi_helpers import (
    get_week_number,
    get_month_string,
    get_quarter_string,
    get_fiscal_year,
)


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def get_description() -> str:
    """Return KPI description."""
    return (
        "SAST Gating Issues – Total SAST security issues (High + Medium severity) per team, "
        "aggregated from AppScan SAST HTML reports. "
        "Source: 'Summary of security issues' section of each project's SAST report. "
        "If a team has multiple scan projects, counts are summed."
    )
def _parse_sast_html(html_path: str) -> int:
    """
    Parse an AppScan SAST HTML report and return the total of
    High + Medium severity issues from the 'Summary of security issues' table.

    Returns 0 if the file is missing, unreadable, or the section is absent.
    """
    if not os.path.exists(html_path):
        print(f"    ⚠ SAST report not found: {html_path}")
        return 0

    try:
        with open(html_path, "r", encoding="utf-8", errors="ignore") as fh:
            content = fh.read()
    except Exception as exc:
        print(f"    ⚠ Failed to read {html_path}: {exc}")
        return 0

    # Locate the 'Summary of security issues' block (between <h3> and </table>).
    section_match = re.search(
        r"Summary of security issues.*?</table>",
        content,
        re.DOTALL | re.IGNORECASE,
    )
    if not section_match:
        print(f"    ⚠ 'Summary of security issues' section not found in {os.path.basename(html_path)}")
        return 0

    section = section_match.group()

    def _extract_count(label: str) -> int:
        m = re.search(
            rf"{re.escape(label)}.*?<td[^>]*>\s*(\d+)\s*</td>",
            section,
            re.DOTALL | re.IGNORECASE,
        )
        return int(m.group(1)) if m else 0

    high   = _extract_count("High severity issues:")
    medium = _extract_count("Medium severity issues:")
    total  = high + medium
    print(f"    ✓ {os.path.basename(html_path)}: High={high}, Medium={medium} → {total}")
    return total


def _load_scan_config(project_root: Path) -> dict:
    """Load config/security_scan_config.json."""
    cfg_path = project_root / "config" / "security_scan_config.json"
    if not cfg_path.exists():
        print(f"  ⚠ Scan config not found: {cfg_path}")
        return {}
    try:
        with open(cfg_path, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except Exception as exc:
        print(f"  ⚠ Failed to read scan config: {exc}")
        return {}


def _build_team_scores(scan_config: dict, scans_sast_dir: Path) -> tuple[dict[str, int], dict[str, list[str]]]:
    """
    Return:
    - team_scores: {team_name: total_sast_count}
      - team_sources: {team_name: ["<project_id>(<count>)", ...]} terminal-only debug trace
    by summing High+Medium across all scan projects mapped to each team.
    """
    team_scores: dict[str, int] = {}
    team_sources: dict[str, list[str]] = {}

    for project in scan_config.get("projects", []):
        pid      = project.get("id", "").strip()
        teams    = project.get("teams", [])
        reports  = project.get("reports", [])

        # Find the SAST report filename for this project
        sast_entry = next((r for r in reports if r.get("type") == "sast"), None)
        if not sast_entry:
            print(f"  ⚠ No SAST report configured for project '{pid}' — skipping")
            continue

        html_path = str(scans_sast_dir / sast_entry["filename"])
        count = _parse_sast_html(html_path)

        for team in teams:
            team_scores[team] = team_scores.get(team, 0) + count
            team_sources.setdefault(team, []).append(f"{pid}({count})")

    return team_scores, team_sources


def _median(values: list[float]) -> float:
    """Return the median of a list; 0.0 if empty."""
    if not values:
        return 0.0
    s = sorted(values)
    n = len(s)
    mid = n // 2
    return float(s[mid] if n % 2 == 1 else (s[mid - 1] + s[mid]) / 2)


# ─────────────────────────────────────────────────────────────────────────────
# Main KPI function
# ─────────────────────────────────────────────────────────────────────────────

def k302(resources_file: str, output_dir: str, fiscal_start_month: int = 4,
         current_date: date | None = None) -> bool:
    """
    K302: SAST Gating Issues aggregated at Team level, propagated to all
    members of the team.

    Args:
        resources_file      Path to Resources.csv
        output_dir          Directory for output files (also used to locate scans/)
        fiscal_start_month  Starting month of fiscal year (default 4 = April)
        current_date        Reference date (default: today)

    Returns:
        True on success, False on failure.
    """
    output_file = os.path.join(output_dir, "k302-data.csv")

    if current_date is None:
        current_date = date.today()

    current_date_str = current_date.strftime("%Y%m%d")

    print(f"\n{'='*60}")
    print(f"KPP K302 - SAST Gating Issues")
    print(f"Date: {current_date_str}")
    print(f"{'='*60}")

    # Derive project root from output_dir (output/ is one level below root)
    project_root = Path(output_dir).parent

    # ── Load resources ────────────────────────────────────────────────────────
    print("Loading resources data...")
    try:
        resources_df = pd.read_csv(resources_file)
        resources = resources_df[["SAPID", "Name", "Team"]].copy()
        resources["SAPID"] = resources["SAPID"].fillna(0).astype(int).astype(str)
        resources = resources[resources["Team"].notna() & (resources["Team"] != "-NA-")]
        print(f"  ✓ Loaded {len(resources)} resources")
    except Exception as exc:
        print(f"  ✗ Error loading resources: {exc}")
        return False

    if resources.empty:
        print("  ✗ No resources data")
        return False

    # ── Load scan configuration and parse SAST HTML reports ──────────────────
    print("Loading scan configuration...")
    scan_config = _load_scan_config(project_root)
    if not scan_config:
        print("  ⚠ No scan configuration found — marking all teams as not configured")
        team_scores: dict[str, int] = {}
        team_sources: dict[str, list[str]] = {}
    else:
        scans_sast_dir = Path(output_dir) / "scans" / "sast"
        print(f"  Parsing SAST reports from: {scans_sast_dir}")
        team_scores, team_sources = _build_team_scores(scan_config, scans_sast_dir)
        print(f"  Team SAST scores: {team_scores}")
        if team_sources:
            print("  Team score contributions (for reference):")
            for team in sorted(team_sources):
                src = " + ".join(team_sources[team])
                print(f"    - {team}: {src} = {team_scores.get(team, 0)}")

    # ── Period labels for the current date ───────────────────────────────────
    current_dt        = pd.Timestamp(current_date)
    current_week      = get_week_number(current_dt)
    current_month     = get_month_string(current_dt)
    current_quarter   = get_quarter_string(current_dt)
    current_fiscal_yr = get_fiscal_year(current_dt, fiscal_start_month)

    # ── Load existing history (for median calculation) ────────────────────────
    print("Loading historical k302 data for median computation...")
    if os.path.exists(output_file):
        try:
            history_df = pd.read_csv(output_file, dtype={"SAPID": str, "Week": str})
            # Drop any rows already recorded for the current week (will be replaced below)
            history_df = history_df[history_df["Week"].astype(str) != str(current_week)]
            print(f"  ✓ Loaded {len(history_df)} historical rows (current week excluded)")
        except Exception as exc:
            print(f"  ⚠ Failed to read existing history: {exc} — starting fresh")
            history_df = pd.DataFrame()
    else:
        history_df = pd.DataFrame()
        print("  ℹ No existing history file — this is the first run")

    configured_teams = set(team_scores.keys())

    # ── Build current-run rows ────────────────────────────────────────────────
    print("Computing per-member values...")
    new_rows = []

    for _, emp in resources.iterrows():
        sapid = str(emp["SAPID"])
        name  = emp["Name"]
        team  = emp["Team"]

        is_configured = team in configured_teams
        weekly_val = float(team_scores.get(team, 0)) if is_configured else None

        # Gather historical weekly values for this person in each period
        if not history_df.empty and "SAPID" in history_df.columns:
            person_hist = history_df[history_df["SAPID"].astype(str) == sapid]
        else:
            person_hist = pd.DataFrame()

        def _period_median(col: str, current_label: str) -> float:
            if weekly_val is None:
                return None
            if person_hist.empty or col not in person_hist.columns:
                return _median([weekly_val])
            past_vals = person_hist[person_hist[col] == current_label]["Weekly"].dropna().tolist()
            return _median(past_vals + [weekly_val])

        monthly_val   = _period_median("Month",   current_month)
        quarterly_val = _period_median("Quarter", current_quarter)
        annual_val    = _period_median("Year",    current_fiscal_yr)

        new_rows.append({
            "CurrentDate": current_date_str,
            "Week":        current_week,
            "Month":       current_month,
            "Quarter":     current_quarter,
            "Year":        current_fiscal_yr,
            "SAPID":       sapid,
            "Name":        name,
            "Weekly":      weekly_val,
            "Monthly":     monthly_val,
            "Quarterly":   quarterly_val,
            "Annual":      annual_val,
            "ConfigurationStatus": "configured" if is_configured else "not_configured",
        })

    new_df = pd.DataFrame(new_rows)

    # ── Merge with history and save ──────────────────────────────────────────
    if not history_df.empty:
        combined = pd.concat([history_df, new_df], ignore_index=True)
    else:
        combined = new_df

    combined.to_csv(output_file, index=False)

    print(f"\n  ✓ Saved {output_file}")
    print(f"    Current run: {len(new_rows)} records  |  Total history: {len(combined)} rows")
    print(f"    Teams with SAST data: {sorted(team_scores.keys())}")
    print(
        f"    Teams with no SAST configuration: "
        f"{sorted(set(resources['Team'].unique()) - set(team_scores.keys()))}"
    )
    return True


# ─────────────────────────────────────────────────────────────────────────────
# CLI entry point (for standalone testing)
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse

    PROJECT_ROOT = Path(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    parser = argparse.ArgumentParser(description="Run KPI K302 – SAST Gating Issues")
    parser.add_argument(
        "--project-root",
        default=str(PROJECT_ROOT),
        help="Path to the TeamSight project root",
    )
    args = parser.parse_args()

    root = Path(args.project_root)
    success = k302(
        resources_file=str(root / "config" / "Resources.csv"),
        output_dir=str(root / "output"),
    )
    sys.exit(0 if success else 1)
