#!/bin/bash
# Quick Start Guide for JIRA History Tracking
# This script demonstrates how to use the new history tracking features

echo "=========================================="
echo "JIRA History Tracking - Quick Start"
echo "=========================================="
echo ""

# Step 1: Fetch JIRA data with changelog
echo "Step 1: Fetching JIRA data with changelog history..."
echo "Command: python src/jira_fetch.py --fetch"
echo ""
echo "This will create:"
echo "  - output/JIRAIssues.csv (current state)"
echo "  - output/JIRAIssues_History.csv (change history)"
echo ""

# Step 2: Analyze bug cycle times
echo "Step 2: Analyze bug cycle times..."
echo "Command: python src/kpp_bug_cycle_time.py"
echo ""
echo "This will create:"
echo "  - output/bug_cycle_time.csv (detailed cycle times)"
echo "  - output/bug_cycle_time_summary.csv (summary by priority)"
echo ""

# Step 3: Track replanning
echo "Step 3: Track replanning for Stories/Epics..."
echo "Command: python src/kpp_replan_tracker.py"
echo ""
echo "This will create:"
echo "  - output/replan_tracker.csv (detailed replan data)"
echo "  - output/replan_tracker_summary.csv (summary by issue type)"
echo "  - output/replan_tracker_by_priority.csv (breakdown by priority)"
echo "  - output/replan_tracker_high_replan.csv (high replan issues)"
echo ""

echo "=========================================="
echo "Additional Commands"
echo "=========================================="
echo ""
echo "Reset all data (start fresh):"
echo "  python src/jira_fetch.py --reset"
echo ""
echo "View help:"
echo "  python src/jira_fetch.py --help"
echo ""

echo "=========================================="
echo "Quick Verification"
echo "=========================================="
echo ""
echo "After running the fetch, verify files exist:"
echo "  ls -lh output/JIRAIssues*.csv"
echo ""
echo "Check history entries:"
echo "  wc -l output/JIRAIssues_History.csv"
echo ""
echo "Preview history data:"
echo "  head -20 output/JIRAIssues_History.csv"
echo ""

echo "=========================================="
echo "What Each Script Provides"
echo "=========================================="
echo ""
echo "Bug Cycle Time Analysis:"
echo "  - Time spent in each status"
echo "  - Total cycle time (days/hours)"
echo "  - Rework count (returns to previous states)"
echo "  - Statistics by priority"
echo ""
echo "Replan Tracker:"
echo "  - Number of sprint changes per issue"
echo "  - Sprint timeline with dates"
echo "  - Replan rate across projects"
echo "  - High-risk issues (>= 3 replans)"
echo ""

echo "=========================================="
echo "For more details, see:"
echo "  docs/HISTORY_TRACKING.md"
echo "=========================================="
